export async function desnutricionNinos() {
  try {
    const data = [
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "CANGALLO",
        puntuacion: 2749,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "CHUSCHI",
        puntuacion: 1321,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "LOS MOROCHUCOS",
        puntuacion: 1928,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "MARIA PARADO DE BELLIDO",
        puntuacion: 1467,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "PARAS",
        puntuacion: 2203,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "TOTOS",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ACOCRO",
        puntuacion: 1493,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ACOS VINCHOS",
        puntuacion: 1200,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ANDRES AVELINO CACERES DORREGARAY",
        puntuacion: 302,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "AYACUCHO",
        puntuacion: 2314,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "CARMEN ALTO",
        puntuacion: 1746,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "CHIARA",
        puntuacion: 813,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "JESUS NAZARENO",
        puntuacion: 1985,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "OCROS",
        puntuacion: 2557,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "PACAYCASA",
        puntuacion: 1758,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "QUINUA",
        puntuacion: 1001,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SAN JOSE DE TICLLAS",
        puntuacion: 3019,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SAN JUAN BAUTISTA",
        puntuacion: 1109,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SANTIAGO DE PISCHA",
        puntuacion: 2683,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SOCOS",
        puntuacion: 2957,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "TAMBILLO",
        puntuacion: 2443,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "VINCHOS",
        puntuacion: 1920,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "CARAPO",
        puntuacion: 255,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SACSAMARCA",
        puntuacion: 2906,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SANCOS",
        puntuacion: 1794,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SANTIAGO DE LUCANAMARCA",
        puntuacion: 1987,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "AYAHUANCO",
        puntuacion: 937,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "CANAYRE",
        puntuacion: 1561,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "CHACA",
        puntuacion: 2024,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "HUAMANGUILLA",
        puntuacion: 1202,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "HUANTA",
        puntuacion: 2463,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "IGUAIN",
        puntuacion: 1519,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "LLOCHEGUA",
        puntuacion: 679,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "LURICOCHA",
        puntuacion: 1578,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "PUCACOLPA",
        puntuacion: 730,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "SANTILLANA",
        puntuacion: 2447,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "PUTIS",
        puntuacion: 2447,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "SIVIA",
        puntuacion: 2895,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "UCHURACCAY",
        puntuacion: 2513,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ANCHIHUAY",
        puntuacion: 1702,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ANCO",
        puntuacion: 2935,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "UNION PROGRESO",
        puntuacion: 295,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "AYNA",
        puntuacion: 1010,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "CHILCAS",
        puntuacion: 688,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "CHUNGUI",
        puntuacion: 1596,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "LUIS CARRANZA",
        puntuacion: 2093,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ORONCCOY",
        puntuacion: 2672,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SAMUGARI",
        puntuacion: 2025,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SAN MIGUEL",
        puntuacion: 3018,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "PATIBAMBA",
        puntuacion: 4121,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "NINABAMBA",
        puntuacion: 142,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SANTA ROSA",
        puntuacion: 1319,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "TAMBO",
        puntuacion: 303,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "AUCARA",
        puntuacion: 2712,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CABANA",
        puntuacion: 2309,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CARMEN SALCEDO",
        puntuacion: 957,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CHAVIÑA",
        puntuacion: 2454,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CHIPAO",
        puntuacion: 810,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "HUAC-HUAS",
        puntuacion: 2491,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LARAMATE",
        puntuacion: 2581,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LEONCIO PRADO",
        puntuacion: 1067,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LLAUTA",
        puntuacion: 2993,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LUCANAS",
        puntuacion: 2663,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "OCAÑA",
        puntuacion: 1056,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "OTOCA",
        puntuacion: 1512,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "PUQUIO",
        puntuacion: 1164,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAISA",
        puntuacion: 87,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANCOS",
        puntuacion: 2954,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN CRISTOBAL",
        puntuacion: 2762,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN JUAN",
        puntuacion: 1213,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN PEDRO",
        puntuacion: 2316,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN PEDRO DE PALCO",
        puntuacion: 997,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANTA ANA DE HUAYCAHUACHO",
        puntuacion: 2028,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANTA LUCIA",
        puntuacion: 2548,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CHUMPI",
        puntuacion: 1269,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CORACORA",
        puntuacion: 1151,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CORONEL CASTAÑEDA",
        puntuacion: 671,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PACAPAUSA",
        puntuacion: 1364,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PULLO",
        puntuacion: 2478,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PUYUSCA",
        puntuacion: 1104,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "SAN FRANCISCO DE RAVACAYCO",
        puntuacion: 2713,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "UPAHUACHO",
        puntuacion: 2551,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "COLTA",
        puntuacion: 2958,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "CORCULLA",
        puntuacion: 1956,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "LAMPA",
        puntuacion: 1483,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "MARCABAMBA",
        puntuacion: 2757,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "OYOLO",
        puntuacion: 1564,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "PARARCA",
        puntuacion: 2198,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "PAUSA",
        puntuacion: 3016,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SAN JAVIER DE ALPABAMBA",
        puntuacion: 1157,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SAN JOSE DE USHUA",
        puntuacion: 689,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SARA SARA",
        puntuacion: 1632,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "BELEN",
        puntuacion: 1285,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "CHALCOS",
        puntuacion: 2731,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "CHILCAYOC",
        puntuacion: 2148,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "HUACAÑA",
        puntuacion: 2432,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "MORCOLLA",
        puntuacion: 2077,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "PAICO",
        puntuacion: 1923,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "QUEROBAMBA",
        puntuacion: 2450,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SAN PEDRO DE LARCAY",
        puntuacion: 1068,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SAN SALVADOR DE QUIJE",
        puntuacion: 2302,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SANTIAGO DE PAUCARAY",
        puntuacion: 2687,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SORAS",
        puntuacion: 2582,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "ALCAMENCA",
        puntuacion: 2211,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "APONGO",
        puntuacion: 1023,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "ASQUIPATA",
        puntuacion: 2992,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "CANARIA",
        puntuacion: 2170,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "CAYARA",
        puntuacion: 1093,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "COLCA",
        puntuacion: 2104,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUAMANQUIQUIA",
        puntuacion: 2855,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUANCAPI",
        puntuacion: 2241,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUANCARAYLLA",
        puntuacion: 1557,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUAYA",
        puntuacion: 1235,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "SARHUA",
        puntuacion: 2827,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "VILCANCHOS",
        puntuacion: 1117,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "ACCOMARCA",
        puntuacion: 2375,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "CARHUANCA",
        puntuacion: 1192,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "CONCEPCION",
        puntuacion: 832,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "HUAMBALPA",
        puntuacion: 1279,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "INDEPENDENCIA",
        puntuacion: 2016,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "SAURAMA",
        puntuacion: 2814,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "VILCAS HUAMAN",
        puntuacion: 1563,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "VISCHONGO",
        puntuacion: 2097,
      },
    ];
    return data;
  } catch (error) {
    console.error("Error en la función desnutricionNinos:", error);
    throw error;
  }
}

export async function AnemiaNinos() {
  try {
    const data = [
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "CANGALLO",
        puntuacion: 3421,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "CHUSCHI",
        puntuacion: 987,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "LOS MOROCHUCOS",
        puntuacion: 2564,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "MARIA PARADO DE BELLIDO",
        puntuacion: 1789,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "PARAS",
        puntuacion: 2934,
      },
      {
        departamento: "Ayacucho",
        provincia: "CANGALLO",
        distrito: "TOTOS",
        puntuacion: 3210,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ACOCRO",
        puntuacion: 1643,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ACOS VINCHOS",
        puntuacion: 1357,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "ANDRES AVELINO CACERES DORREGARAY",
        puntuacion: 456,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "AYACUCHO",
        puntuacion: 2789,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "CARMEN ALTO",
        puntuacion: 2012,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "CHIARA",
        puntuacion: 923,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "JESUS NAZARENO",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "OCROS",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "PACAYCASA",
        puntuacion: 1987,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "QUINUA",
        puntuacion: 1123,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SAN JOSE DE TICLLAS",
        puntuacion: 3567,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SAN JUAN BAUTISTA",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SANTIAGO DE PISCHA",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "SOCOS",
        puntuacion: 3278,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "TAMBILLO",
        puntuacion: 2765,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUAMANGA",
        distrito: "VINCHOS",
        puntuacion: 2134,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "CARAPO",
        puntuacion: 387,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SACSAMARCA",
        puntuacion: 3124,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SANCOS",
        puntuacion: 2045,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANCA SANCOS",
        distrito: "SANTIAGO DE LUCANAMARCA",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "AYAHUANCO",
        puntuacion: 1056,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "CANAYRE",
        puntuacion: 1765,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "CHACA",
        puntuacion: 2347,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "HUAMANGUILLA",
        puntuacion: 1432,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "HUANTA",
        puntuacion: 2789,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "IGUAIN",
        puntuacion: 1678,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "LLOCHEGUA",
        puntuacion: 845,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "LURICOCHA",
        puntuacion: 1893,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "PUCACOLPA",
        puntuacion: 912,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "SANTILLANA",
        puntuacion: 2654,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "PUTIS",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "SIVIA",
        puntuacion: 3214,
      },
      {
        departamento: "Ayacucho",
        provincia: "HUANTA",
        distrito: "UCHURACCAY",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ANCHIHUAY",
        puntuacion: 1876,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ANCO",
        puntuacion: 3345,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "UNION PROGRESO",
        puntuacion: 423,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "AYNA",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "CHILCAS",
        puntuacion: 876,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "CHUNGUI",
        puntuacion: 1789,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "LUIS CARRANZA",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "ORONCCOY",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SAMUGARI",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SAN MIGUEL",
        puntuacion: 3456,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "PATIBAMBA",
        puntuacion: 4321,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "NINABAMBA",
        puntuacion: 234,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "SANTA ROSA",
        puntuacion: 1567,
      },
      {
        departamento: "Ayacucho",
        provincia: "LA MAR",
        distrito: "TAMBO",
        puntuacion: 456,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "AUCARA",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CABANA",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CARMEN SALCEDO",
        puntuacion: 1123,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CHAVIÑA",
        puntuacion: 2789,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "CHIPAO",
        puntuacion: 945,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "HUAC-HUAS",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LARAMATE",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LEONCIO PRADO",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LLAUTA",
        puntuacion: 3345,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "LUCANAS",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "OCAÑA",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "OTOCA",
        puntuacion: 1678,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "PUQUIO",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAISA",
        puntuacion: 123,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANCOS",
        puntuacion: 3214,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN CRISTOBAL",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN JUAN",
        puntuacion: 1456,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN PEDRO",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SAN PEDRO DE PALCO",
        puntuacion: 1123,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANTA ANA DE HUAYCAHUACHO",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "LUCANAS",
        distrito: "SANTA LUCIA",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CHUMPI",
        puntuacion: 1456,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CORACORA",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "CORONEL CASTAÑEDA",
        puntuacion: 789,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PACAPAUSA",
        puntuacion: 1567,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PULLO",
        puntuacion: 2789,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "PUYUSCA",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "SAN FRANCISCO DE RAVACAYCO",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "PARINACOCHAS",
        distrito: "UPAHUACHO",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "COLTA",
        puntuacion: 3214,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "CORCULLA",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "LAMPA",
        puntuacion: 1678,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "MARCABAMBA",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "OYOLO",
        puntuacion: 1789,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "PARARCA",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "PAUSA",
        puntuacion: 3456,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SAN JAVIER DE ALPABAMBA",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SAN JOSE DE USHUA",
        puntuacion: 876,
      },
      {
        departamento: "Ayacucho",
        provincia: "PAUCAR DEL SARA SARA",
        distrito: "SARA SARA",
        puntuacion: 1876,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "BELEN",
        puntuacion: 1456,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "CHALCOS",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "CHILCAYOC",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "HUACAÑA",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "MORCOLLA",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "PAICO",
        puntuacion: 2123,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "QUEROBAMBA",
        puntuacion: 2789,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SAN PEDRO DE LARCAY",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SAN SALVADOR DE QUIJE",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SANTIAGO DE PAUCARAY",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "SUCRE",
        distrito: "SORAS",
        puntuacion: 2876,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "ALCAMENCA",
        puntuacion: 2456,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "APONGO",
        puntuacion: 1123,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "ASQUIPATA",
        puntuacion: 3214,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "CANARIA",
        puntuacion: 2345,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "CAYARA",
        puntuacion: 1234,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "COLCA",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUAMANQUIQUIA",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUANCAPI",
        puntuacion: 2567,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUANCARAYLLA",
        puntuacion: 1789,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "HUAYA",
        puntuacion: 1456,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "SARHUA",
        puntuacion: 2987,
      },
      {
        departamento: "Ayacucho",
        provincia: "VICTOR FAJARDO",
        distrito: "VILCANCHOS",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "ACCOMARCA",
        puntuacion: 2678,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "CARHUANCA",
        puntuacion: 1345,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "CONCEPCION",
        puntuacion: 945,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "HUAMBALPA",
        puntuacion: 1456,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "INDEPENDENCIA",
        puntuacion: 2234,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "SAURAMA",
        puntuacion: 3012,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "VILCAS HUAMAN",
        puntuacion: 1789,
      },
      {
        departamento: "Ayacucho",
        provincia: "VILCAS HUAMAN",
        distrito: "VISCHONGO",
        puntuacion: 2345,
      },
    ];
    return data;
  } catch (error) {
    console.error("Error en la función desnutricionNinos:", error);
    throw error;
  }
}
