"use client";
import GeoJsonSvg from "@/components/map/GeoJsonSvg";
import { useState } from "react";

const Page: React.FC = () => {
  const [provincia, setProvincias] = useState("all");
  const distritos = [
    { nombre: "CANGALLO", puntuacion: 2749 },
    { nombre: "CHUSCHI", puntuacion: 1321 },
    { nombre: "LOS MOROCHUCOS", puntuacion: 1928 },
    { nombre: "MARIA PARADO DE BELLIDO", puntuacion: 1467 },
    { nombre: "PARAS", puntuacion: 2203 },
    { nombre: "TOTOS", puntuacion: 2678 },
    { nombre: "ACOCRO", puntuacion: 1493 },
    { nombre: "ACOS VINCHOS", puntuacion: 1200 },
    { nombre: "ANDRES AVELINO CACERES DORREGARAY", puntuacion: 302 },
    { nombre: "AYACUCHO", puntuacion: 2314 },
    { nombre: "CARMEN ALTO", puntuacion: 1746 },
    { nombre: "CHIARA", puntuacion: 813 },
    { nombre: "JESUS NAZARENO", puntuacion: 1985 },
    { nombre: "OCROS", puntuacion: 2557 },
    { nombre: "PACAYCASA", puntuacion: 1758 },
    { nombre: "QUINUA", puntuacion: 1001 },
    { nombre: "SAN JOSE DE TICLLAS", puntuacion: 3019 },
    { nombre: "SAN JUAN BAUTISTA", puntuacion: 1109 },
    { nombre: "SANTIAGO DE PISCHA", puntuacion: 2683 },
    { nombre: "SOCOS", puntuacion: 2957 },
    { nombre: "TAMBILLO", puntuacion: 2443 },
    { nombre: "VINCHOS", puntuacion: 1920 },
    { nombre: "CARAPO", puntuacion: 255 },
    { nombre: "SACSAMARCA", puntuacion: 2906 },
    { nombre: "SANCOS", puntuacion: 1794 },
    { nombre: "SANTIAGO DE LUCANAMARCA", puntuacion: 1987 },
    { nombre: "AYAHUANCO", puntuacion: 937 },
    { nombre: "CANAYRE", puntuacion: 1561 },
    { nombre: "CHACA", puntuacion: 2024 },
    { nombre: "HUAMANGUILLA", puntuacion: 1202 },
    { nombre: "HUANTA", puntuacion: 2463 },
    { nombre: "IGUAIN", puntuacion: 1519 },
    { nombre: "LLOCHEGUA", puntuacion: 679 },
    { nombre: "LURICOCHA", puntuacion: 1578 },
    { nombre: "PUCACOLPA", puntuacion: 730 },
    { nombre: "SANTILLANA", puntuacion: 2447 },
    { nombre: "SIVIA", puntuacion: 2895 },
    { nombre: "UCHURACCAY", puntuacion: 2513 },
    { nombre: "ANCHIHUAY", puntuacion: 1702 },
    { nombre: "ANCO", puntuacion: 2935 },
    { nombre: "AYNA", puntuacion: 1010 },
    { nombre: "CHILCAS", puntuacion: 688 },
    { nombre: "CHUNGUI", puntuacion: 1596 },
    { nombre: "LUIS CARRANZA", puntuacion: 2093 },
    { nombre: "ORONCCOY", puntuacion: 2672 },
    { nombre: "SAMUGARI", puntuacion: 2025 },
    { nombre: "SAN MIGUEL", puntuacion: 3018 },
    { nombre: "SANTA ROSA", puntuacion: 1319 },
    { nombre: "TAMBO", puntuacion: 303 },
    { nombre: "AUCARA", puntuacion: 2712 },
    { nombre: "CABANA", puntuacion: 2309 },
    { nombre: "CARMEN SALCEDO", puntuacion: 957 },
    { nombre: "CHAVIÑA", puntuacion: 2454 },
    { nombre: "CHIPAO", puntuacion: 810 },
    { nombre: "HUAC-HUAS", puntuacion: 2491 },
    { nombre: "LARAMATE", puntuacion: 2581 },
    { nombre: "LEONCIO PRADO", puntuacion: 1067 },
    { nombre: "LLAUTA", puntuacion: 2993 },
    { nombre: "LUCANAS", puntuacion: 2663 },
    { nombre: "OCAÑA", puntuacion: 1056 },
    { nombre: "OTOCA", puntuacion: 1512 },
    { nombre: "PUQUIO", puntuacion: 1164 },
    { nombre: "SAISA", puntuacion: 87 },
    { nombre: "SANCOS", puntuacion: 2954 },
    { nombre: "SAN CRISTOBAL", puntuacion: 2762 },
    { nombre: "SAN JUAN", puntuacion: 1213 },
    { nombre: "SAN PEDRO", puntuacion: 2316 },
    { nombre: "SAN PEDRO DE PALCO", puntuacion: 997 },
    { nombre: "SANTA ANA DE HUAYCAHUACHO", puntuacion: 2028 },
    { nombre: "SANTA LUCIA", puntuacion: 2548 },
    { nombre: "CHUMPI", puntuacion: 1269 },
    { nombre: "CORACORA", puntuacion: 1151 },
    { nombre: "CORONEL CASTAÑEDA", puntuacion: 671 },
    { nombre: "PACAPAUSA", puntuacion: 1364 },
    { nombre: "PULLO", puntuacion: 2478 },
    { nombre: "PUYUSCA", puntuacion: 1104 },
    { nombre: "SAN FRANCISCO DE RAVACAYCO", puntuacion: 2713 },
    { nombre: "UPAHUACHO", puntuacion: 2551 },
    { nombre: "COLTA", puntuacion: 2958 },
    { nombre: "CORCULLA", puntuacion: 1956 },
    { nombre: "LAMPA", puntuacion: 1483 },
    { nombre: "MARCABAMBA", puntuacion: 2757 },
    { nombre: "OYOLO", puntuacion: 1564 },
    { nombre: "PARARCA", puntuacion: 2198 },
    { nombre: "PAUSA", puntuacion: 3016 },
    { nombre: "SAN JAVIER DE ALPABAMBA", puntuacion: 1157 },
    { nombre: "SAN JOSE DE USHUA", puntuacion: 689 },
    { nombre: "SARA SARA", puntuacion: 1632 },
    { nombre: "BELEN", puntuacion: 1285 },
    { nombre: "CHALCOS", puntuacion: 2731 },
    { nombre: "CHILCAYOC", puntuacion: 2148 },
    { nombre: "HUACAÑA", puntuacion: 2432 },
    { nombre: "MORCOLLA", puntuacion: 2077 },
    { nombre: "PAICO", puntuacion: 1923 },
    { nombre: "QUEROBAMBA", puntuacion: 2450 },
    { nombre: "SAN PEDRO DE LARCAY", puntuacion: 1068 },
    { nombre: "SAN SALVADOR DE QUIJE", puntuacion: 2302 },
    { nombre: "SANTIAGO DE PAUCARAY", puntuacion: 2687 },
    { nombre: "SORAS", puntuacion: 2582 },
    { nombre: "ALCAMENCA", puntuacion: 2211 },
    { nombre: "APONGO", puntuacion: 1023 },
    { nombre: "ASQUIPATA", puntuacion: 2992 },
    { nombre: "CANARIA", puntuacion: 2170 },
    { nombre: "CAYARA", puntuacion: 1093 },
    { nombre: "COLCA", puntuacion: 2104 },
    { nombre: "HUAMANQUIQUIA", puntuacion: 2855 },
    { nombre: "HUANCAPI", puntuacion: 2241 },
    { nombre: "HUANCARAYLLA", puntuacion: 1557 },
    { nombre: "HUAYA", puntuacion: 1235 },
    { nombre: "SARHUA", puntuacion: 2827 },
    { nombre: "VILCANCHOS", puntuacion: 1117 },
    { nombre: "ACCOMARCA", puntuacion: 2375 },
    { nombre: "CARHUANCA", puntuacion: 1192 },
    { nombre: "CONCEPCION", puntuacion: 832 },
    { nombre: "HUAMBALPA", puntuacion: 1279 },
    { nombre: "INDEPENDENCIA", puntuacion: 2016 },
    { nombre: "SAURAMA", puntuacion: 2814 },
    { nombre: "VILCAS HUAMAN", puntuacion: 1563 },
    { nombre: "VISCHONGO", puntuacion: 2097 }
  ];
  

  return (
    <div className="h-full w-full flex items-center justify-center bg-gray-100 pt-12">
      <GeoJsonSvg
        type={provincia}
        distritos={distritos}
        setProvincias={setProvincias}
      />
    </div>
  );
};

export default Page;
